server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 101.37.23.54:3333
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719  #默认8719，假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口
      web-context-unify: false # 关闭 Context 上下文整合

management:
  endpoints:
    web:
      exposure:
        include: '*'