logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  level:
    com.itheima: debug

spring:
  rabbitmq:
    host: 101.37.23.54
    port: 5672
    virtual-host: /ovo
    username: ovo
    password: weixiao
    # 生产者可靠性；发送失败重试
    connection-timeout: 1s # 设置MQ的连接超时时间
    template:
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 1000ms # 失败后的初始等待时间
        multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
        max-attempts: 3 # 最大重试次数

    # 生产者可靠性；生产者确认
#    publisher-confirm-type: correlated # 开启publisher confirm机制，并设置confirm类型
#    publisher-returns: true # 开启publisher return机制