server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

spring:
  application:
    name: cloud-provider-hystrix-order

feign:
  hystrix:
    enabled: false

# 设置 ribbon
ribbon:
  ConnectTimeout: 5000 # 设置 ribbon 连接超时时间
  ReadTimeout: 5000 # 设置 ribbon 连接读取时间


